### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by brahimdidi** [saied2035/leaderboard#4]
Hello Saied great job working on your code, however, I would like to point out some points.

- The styling on hover of the li (.list-item) is overflowing and the text can not be read.
- It would be better if you added max length to the inputs so your text does not overflow.

**Comment by saied2035** [comment]
**Thanks for reviewing my project.** 👍  

**I solved the notes. you can check it [here](https://saied2035.github.io/leaderboard/)**

**Comment by brahimdidi** [comment]
Hello
